### ISSUE TITLE
Compatibility problem in prasing input event file

### ISSUE THREAD

**Issue by mangost** [bewantbe/point-neuron-network-simulator#2]
Giving an file with Windows style line break, it works fine
Giving Unix style line break while running on WIndows, it only read the first line

**Comment by bewantbe** [comment]
There is no problem to use either Windows style (CR LF) or Unix style (LF) line ending in Windows (or Linux) in my tests.

The only problematic line ending is the Macintosh style (CR), which `ifstream::getline` seems fail in this case.

The CR line ending is now history (<=Macintosh OS 9, 16 years ago), I don't see any needs to support it. i.e. use '\n' instead of '\r' for your line ending.
